### PR TITLE
Enable SQL result parsing for EUI component on Mac (#222)

### PR DESCRIPTION
**Pull request by coditect**
I implemented SQLite parsing via the CLI for the EUI component on Mac using the HB Read Tabular Data component as a template.

I also added a small fix for cases when the _sql input was a string rather than a list of strings so the component doesn't attempt to open each character in the script path as if it were a separate file.

### CODE REVIEW

**Review by chriswmackey — COMMENTED** [review]
Thanks, @coditect . I appreciate the PR and you have the right idea with using the result group of the CLI but I had a different command in mind for this case. I was thinking to [modify this command]https://www.ladybug.tools/honeybee-energy/docs/cli/result.html#honeybee-energy-result-energy-use-intensity) or produce a modified alternative of it so that you can pass multiple sql file arguments instead of a folder. This way, the component has the same functionality on Mac and Windows where you can use it to compute EUI across multiple models. Also, this way, you can make just one CLI call instead of two, which will keep things a little more efficient.

I wasn't going to be able to get to it until later in the week, though, so there's merit in just merging this in so that there's a fix for now. But, to do so, the PR should include the .ghuser object and the JSON representation in addition to the .py file. You can export all of these files together using the "LB Export UserObject" component.

Just re-request my review if you end up pushing the other files and I'll merge it in.

**Comment by coditect** [comment]
@chriswmackey, I modified the `energy-use-intensity` command as you suggested.

This PR now depends on ladybug-tools/honeybee-energy#642.

**Comment by chriswmackey** [comment]
Thank @coditect . I reviewed the honeybee-energy PR. Once things get resolved over there, then I'll re-review this one and we can merge it.

**Review by chriswmackey — CHANGES_REQUESTED** [review]
Thanks again, @coditect .  The export of the user object and JSON look good and the implementation that you did to get everything to run on Mac looks flawless. However, I think we would prefer to still use the `SQLiteResult` directly on Windows machines. Similar to [what we do on all of the other result-parsing components like you see here](https://github.com/ladybug-tools/honeybee-grasshopper-energy/blob/master/honeybee_grasshopper_energy/src/HB%20Read%20Custom%20Result.py#L66-L69).

I know that using the CLI vs the class directly has a negligible impact on the performance of this case and we are making the code longer by having both options but, if Rhino for Mac ever supports the use of `sqlite3` natively, I think I might prefer to simplify everything to use just the class directly instead of the CLI. So it's useful to have the older code here for this case. Also, even if that never happens, I think having a sample of how to use the class directly is an important educational resource for people looking at the component and trying to create a modified version of it for their own purposes.

So, if you could do a check for the `os.name` at the top of the component so that we keep the same behavior on Windows and then run your new code whenever `os.name` is not `'nt'`, then we can merge the PR here.

**Comment by coditect** [comment]
I restored the code that uses `SQLiteResult` on Windows.

**Review by chriswmackey — APPROVED** [review]
This looks great, @coditect . Thank you, again.
Merged!

**Pull request merged**
